class AuthError(Exception):
    """Ошибка при авторизации или работе с запросами"""
    pass
